// A short, for-fun "temperament" reading for each of the 88 official IAU
// constellations — not mythology (see constellationlore.js for that) and not
// real astrology (only 12 of these 88 are zodiac signs; this treats every
// constellation, official or a customer's own private one, as worth reading
// the same way). Every entry is written as a plain, concrete predicate
// phrase meant to complete the sentence "{title} is ___" (see
// buildConstellationAstrology in index.html, which builds exactly that
// sentence, naming the customer's own constellation directly rather than
// talking about "the pattern" or "the constellation" in the abstract) — kept
// to plain character traits rather than metaphor, and to qualities rather
// than actions, since a customer's own constellation can be anything (a
// pet, a house, a name, an object) and a quality ("steady", "hard to miss")
// reads naturally for any of those where an action ("decides to", "chooses
// to") would only really fit a person.
window.CONSTELLATION_ASTROLOGY = {
  "Andromeda": "steady under pressure — the kind that endures a difficult situation it didn't choose, and comes through changed but intact. Doesn't dwell on it, but it shows, quietly, as resilience.",
  "Antlia": "unpretentious and practical, with nothing to prove. Gets on with things quietly rather than looking for credit.",
  "Apus": "bright and a little hard to pin down — reads as effortless from a distance, more interesting the closer you look.",
  "Aquarius": "generous, more comfortable giving than receiving. Tends to keep everyone else's needs met, sometimes at its own expense.",
  "Aquila": "direct and capable — takes on responsibility easily and moves fast once the goal is clear.",
  "Ara": "reliable about commitments — slow to promise something, but treats every promise as binding once made.",
  "Aries": "quick to act, sometimes before thinking it through. Leads with instinct, rarely comfortable waiting its turn.",
  "Auriga": "capable of juggling several responsibilities at once without dropping any of them — a little overloaded, but rarely complains.",
  "Bootes": "patient and watchful, comfortable moving at someone else's pace for as long as it takes. Not in a hurry.",
  "Caelum": "sparse and unadorned, with nothing extra in it — plain, functional, no interest in decoration.",
  "Camelopardalis": "an unusual combination of traits that somehow works, comfortable not fitting neatly into one category.",
  "Cancer": "easy to underestimate, but shows loyalty through action rather than words — takes a hit for someone else without making a show of it.",
  "Canes Venatici": "eager and a little restless, happiest with a clear goal to chase and someone steady leading the way.",
  "Canis Major": "hard to miss — arrives first, and isn't shy about being seen.",
  "Canis Minor": "small but reliable, good at giving an early, useful warning that something bigger is coming.",
  "Capricornus": "adaptable under pressure — improvises its way out of a bad spot even when the result looks a little unconventional.",
  "Carina": "unglamorous but load-bearing, doing the real work quietly rather than looking for recognition.",
  "Cassiopeia": "confident, sometimes overconfident, and draws attention naturally — for better and occasionally for worse.",
  "Centaurus": "capable of both sharp instinct and real wisdom, and tends to be defined by which one it leads with at a given moment.",
  "Cepheus": "steady and unshowy, holding a household or group together from the background rather than the spotlight.",
  "Cetus": "larger and slower-moving than it first appears — more patient than its reputation suggests.",
  "Chamaeleon": "adaptable, changes to fit its surroundings rather than resisting them, comfortable being hard to pin down.",
  "Circinus": "precise, more interested in getting the details exactly right than in being noticed doing it.",
  "Columba": "good news in a difficult moment — shows up right when it's needed, after everyone else has run out of options.",
  "Coma Berenices": "generous to the point of real sacrifice, without expecting anything in return.",
  "Corona Australis": "unremarkable at first glance but consistent and recognizable, with no dramatic backstory required.",
  "Corona Borealis": "values what's freely given over what's won by force, and doesn't wear it as a trophy.",
  "Corvus": "prone to procrastination and a convenient excuse — talks its way out of trouble, not always convincingly.",
  "Crater": "at ease with near-misses — stays close to what it wants without letting the distance turn bitter.",
  "Crux": "small but essential — became indispensable through position, not size.",
  "Cygnus": "capable of real reinvention, and makes the change look graceful rather than difficult.",
  "Delphinus": "helpful at exactly the right moment, generous without needing credit for it.",
  "Dorado": "fast-moving and hard to pin down, leaves an impression before anyone can catch up.",
  "Draco": "watchful and protective, doesn't relax easily when something valuable is at stake.",
  "Equuleus": "quietly present, easy to overlook even by people looking for it — undersold rather than absent.",
  "Eridanus": "shaped by having once lost control of something important, and taking the long way back since.",
  "Fornax": "purely functional, more interested in doing the work than in being recognized for it.",
  "Gemini": "loyal enough to change the terms of its own situation for someone else's sake.",
  "Grus": "patient and watchful, comfortable standing still until the moment actually calls for movement.",
  "Hercules": "strong, but surprisingly unshowy about it — does the hardest work quietly.",
  "Horologium": "steady and unremarkable, reliable simply by keeping to a rhythm rather than seeking attention.",
  "Hydra": "hard to finish off — persistent enough that a single setback rarely settles anything.",
  "Hydrus": "comfortable being the lesser-known half of a pair, without needing to compete for attention.",
  "Indus": "curious about the unfamiliar, defined more by what it's encountered than by caution.",
  "Lacerta": "modest by design, fitting neatly into whatever space is available rather than demanding more.",
  "Leo": "confident, sometimes to the point of overconfidence — comfortable leading, occasionally needing a reminder that it isn't invulnerable.",
  "Leo Minor": "connected to something more famous, but has no real interest in living up to a bigger name.",
  "Lepus": "quick and evasive, better at avoiding a confrontation than winning one outright.",
  "Libra": "preoccupied with fairness, uncomfortable until a decision feels balanced on both sides.",
  "Lupus": "intense, generally in service of someone or something else rather than for its own sake.",
  "Lynx": "sharp and observant, easy to underestimate at a glance but worth a closer look.",
  "Lyra": "known for one distinctive gift, the kind people remember long after the moment it was offered.",
  "Mensa": "grounded and literal, staying steady under whatever gathers around it.",
  "Microscopium": "detail-oriented, more interested in the fine print than the big picture.",
  "Monoceros": "built around one distinctive feature, without needing to be flashy anywhere else.",
  "Musca": "small and easy to dismiss, unbothered by being unusual as long as it's genuinely itself.",
  "Norma": "precise almost to a fault, willing to give ground if that's what getting it right requires.",
  "Octans": "holds down an essential, unglamorous role nobody else is positioned to do, without complaint.",
  "Ophiuchus": "comfortable handling something others find dangerous, because it has actually mastered it rather than merely tolerating it.",
  "Orion": "confident to the point of overreach, occasionally undone by its own certainty, but hard to miss in any room.",
  "Pavo": "displays without apology, knows its own strengths, and isn't shy about showing them.",
  "Pegasus": "built to help someone else go further than they could alone, and strains when that ambition overreaches.",
  "Perseus": "resourceful under pressure, solves a difficult problem sideways rather than head-on, and moves fast afterward.",
  "Phoenix": "resilient to the point of genuine reinvention — endings don't tend to stick.",
  "Pictor": "precise and a little self-effacing, more comfortable supporting someone else's moment than holding the center of it.",
  "Pisces": "keeps whoever it's attached to close, even in the middle of a difficult situation.",
  "Piscis Austrinus": "older and more substantial than it first appears, with more history behind it than it usually gets credit for.",
  "Puppis": "carries the marks of a bigger past it was once part of, comfortable being only a fragment of the original whole.",
  "Pyxis": "rarely lost, oriented and dependable even when the rest of the situation isn't.",
  "Reticulum": "measured and careful, checking twice before committing rather than moving fast.",
  "Sagitta": "decisive and quick — one clear action rather than an ongoing process.",
  "Sagittarius": "patient and pointed, holding steady on a goal until the moment is exactly right.",
  "Scorpius": "capable of a real sting when provoked, but otherwise more defensive than aggressive despite its reputation.",
  "Sculptor": "patient with the unglamorous middle of a project, more interested in the tools of making than in a finished story.",
  "Scutum": "protective, offered in gratitude to someone it owes a debt to rather than for its own sake.",
  "Serpens": "comfortable being split or discontinuous, held together by whoever grips it firmly in the middle.",
  "Sextans": "loyal to a method that works, unbothered by whether it's the newest way to do things.",
  "Taurus": "slow to trust, but carries whatever it commits to a long way once it does.",
  "Telescopium": "oriented outward, more interested in what's distant than in itself.",
  "Triangulum": "simple and exact, needing no embellishment to be recognizable.",
  "Triangulum Australe": "a more precise version of something familiar, improving on a known shape rather than inventing a new one.",
  "Tucana": "distinctive at a glance, memorable by feature rather than by size.",
  "Ursa Major": "protective, sometimes clumsily so — quick to keep its own close and safe, even at some cost to itself.",
  "Ursa Minor": "small and unshowy, but genuinely useful — depended on for steadiness rather than brightness, and kept close to family rather than left to wander.",
  "Vela": "content without needing individual recognition, doing real work in service of something larger it's part of.",
  "Virgo": "seasonal in temperament, capable of real withdrawal and real generosity depending on where it is in its own cycle.",
  "Volans": "prone to a sudden, surprising break from routine, rather than a sustained one.",
  "Vulpecula": "modest and a little scrappy, comfortable staying low-key even when something genuinely notable sits quietly within it.",
};
