// Supplementary facts (distance, spectral type, notable features) for the
// brightest, most commonly-named stars — used to enrich the per-star
// descriptions in the viewer's summary screen. Distances are commonly-cited
// light-year figures (rounded); several very distant/supergiant stars have
// genuinely uncertain distances in the professional literature, marked "~".
// Deliberately NOT exhaustive: the full catalog (stars.js, used by the
// finder) has ~1660 entries down to fairly obscure Bayer-letter stars, and
// this only covers named stars well-documented enough to state facts about
// with confidence. Anything missing here just falls back to name +
// constellation + magnitude in the viewer — no guessed numbers.
window.STAR_INFO = {
  "Sirius": { distanceLy: 8.6, type: "A1V — white main-sequence star", note: "The brightest star in the night sky. Has a white dwarf companion, Sirius B." },
  "Arcturus": { distanceLy: 37, type: "K1.5III — orange giant", note: "The brightest star in the northern celestial hemisphere." },
  "Vega": { distanceLy: 25, type: "A0V — white main-sequence star", note: "Surrounded by a debris disk; one of the most-studied stars in the sky." },
  "Capella": { distanceLy: 43, type: "G+G — binary yellow giants", note: "Actually a system of two yellow giant stars orbiting each other closely." },
  "Rigel": { distanceLy: 860, type: "B8Ia — blue supergiant", note: "One of the most luminous stars known, despite its great distance." },
  "Procyon": { distanceLy: 11.5, type: "F5IV-V — white-yellow subgiant", note: "Has a faint white dwarf companion, Procyon B." },
  "Betelgeuse": { distanceLy: 550, type: "M1-2Ia — red supergiant", note: "Near the end of its life; will eventually explode as a supernova. Distance is only roughly known." },
  "Altair": { distanceLy: 17, type: "A7V — white main-sequence star", note: "Spins so fast it's noticeably flattened at the poles." },
  "Aldebaran": { distanceLy: 65, type: "K5III — orange giant", note: "Known as the \"eye of the bull\" in Taurus." },
  "Spica": { distanceLy: 250, type: "B1III-IV — blue giant binary", note: "A close binary pair of hot blue giant stars." },
  "Antares": { distanceLy: 550, type: "M1.5Iab — red supergiant", note: "One of the largest stars visible to the naked eye. Distance only roughly known." },
  "Pollux": { distanceLy: 34, type: "K0IIIb — orange giant", note: "Known to host at least one confirmed exoplanet." },
  "Fomalhaut": { distanceLy: 25, type: "A3V — white main-sequence star", note: "Surrounded by a prominent debris disk." },
  "Deneb": { distanceLy: 2600, type: "A2Ia — blue-white supergiant", note: "So luminous it's easily visible despite being one of the most distant naked-eye stars. Distance is quite uncertain." },
  "Regulus": { distanceLy: 79, type: "B8IVn — blue-white subgiant", note: "A multiple star system; the main star spins extremely fast." },
  "Adhara": { distanceLy: 430, type: "B2II — blue giant", note: "Radiates strongly in ultraviolet light." },
  "Castor": { distanceLy: 51, type: "A1V+A2Vm — multiple system", note: "Actually six stars in three pairs, not a single star." },
  "Bellatrix": { distanceLy: 245, type: "B2III — blue giant" },
  "Alnath": { distanceLy: 130, type: "B7III — blue-white giant" },
  "Alnilam": { distanceLy: 2000, type: "B0Ia — blue supergiant", note: "The middle star of Orion's Belt." },
  "Alnitak": { distanceLy: 800, type: "O9.5Ib — blue supergiant", note: "The easternmost star of Orion's Belt; a triple star system." },
  "Alioth": { distanceLy: 81, type: "A0p — peculiar white star", note: "Part of the Big Dipper's handle." },
  "Mirphak": { distanceLy: 510, type: "F5Ib — yellow-white supergiant", note: "The brightest star in Perseus." },
  "Dubhe": { distanceLy: 124, type: "K1III — orange giant", note: "One of the Big Dipper's two \"pointer stars\"." },
  "Wezen": { distanceLy: 1600, type: "F8Ia — yellow-white supergiant" },
  "Alkaid": { distanceLy: 101, type: "B3V — blue-white main-sequence star", note: "The end star of the Big Dipper's handle." },
  "Menkalinan": { distanceLy: 82, type: "A2IV — binary system" },
  "Alhena": { distanceLy: 109, type: "A1IV — white subgiant" },
  "Polaris": { distanceLy: 445, type: "F7Ib — yellow supergiant", note: "The North Star — nearly fixed above the north celestial pole. Actually a Cepheid variable in a triple system." },
  "Mirzam": { distanceLy: 500, type: "B1II-III — blue giant" },
  "Alphard": { distanceLy: 177, type: "K3II-III — orange giant" },
  "Hamal": { distanceLy: 66, type: "K2III — orange giant" },
  "Algieba": { distanceLy: 126, type: "K0III+G7III — binary giant pair" },
  "Diphda": { distanceLy: 96, type: "K0III — orange giant" },
  "Nunki": { distanceLy: 228, type: "B2.5V — blue-white main-sequence star" },
  "Alpheratz": { distanceLy: 97, type: "B8IVpMnHg — chemically peculiar star", note: "Shared historically between the constellations Andromeda and Pegasus." },
  "Mirach": { distanceLy: 197, type: "M0III — red giant" },
  "Saiph": { distanceLy: 650, type: "B0.5Ia — blue supergiant" },
  "Kochab": { distanceLy: 130, type: "K4III — orange giant", note: "Was the pole star around 1000 BCE, before Polaris." },
  "Rasalhague": { distanceLy: 47, type: "A5III — white giant" },
  "Algol": { distanceLy: 93, type: "B8V — eclipsing binary", note: "The famous \"Demon Star\" — visibly dims every ~3 days as one star eclipses the other." },
  "Almaak": { distanceLy: 355, type: "K3IIb — multiple system", note: "A striking telescopic double star with contrasting gold and blue colors." },
  "Denebola": { distanceLy: 36, type: "A3V — white main-sequence star" },
  "Cih": { distanceLy: 610, type: "B0.5IV — variable blue-white star", note: "Part of Cassiopeia's distinctive \"W\" shape." },
  "Alphekka": { distanceLy: 75, type: "A0V — white main-sequence star" },
  "Mizar": { distanceLy: 78, type: "A2V — multiple system", note: "Forms a famous naked-eye double with nearby Alcor, and is itself a multiple star." },
  "Sadr": { distanceLy: 1800, type: "F8Iab — yellow-white supergiant" },
  "Shedir": { distanceLy: 228, type: "K0IIIa — orange giant" },
  "Etamin": { distanceLy: 148, type: "K5III — orange giant" },
  "Mintaka": { distanceLy: 1200, type: "O9.5II — eclipsing binary", note: "The westernmost star of Orion's Belt." },
  "Caph": { distanceLy: 55, type: "F2III-IV — white-yellow giant" },
  "Dschubba": { distanceLy: 400, type: "B0.3IV — blue subgiant binary" },
  "Merak": { distanceLy: 79, type: "A1V — white main-sequence star", note: "One of the Big Dipper's two \"pointer stars\"." },
  "Izar": { distanceLy: 210, type: "K0II-III+A2V — double star", note: "A visually striking telescopic double, sometimes called Pulcherrima (\"most beautiful\")." },
  "Enif": { distanceLy: 690, type: "K2Ib — orange supergiant" },
  "Phad": { distanceLy: 84, type: "A0V — white main-sequence star" },
  "Scheat": { distanceLy: 196, type: "M2.5II-III — red giant" },
  "Aludra": { distanceLy: 2000, type: "B5Ia — blue supergiant" },
  "Alderamin": { distanceLy: 49, type: "A7IV-V — white subgiant", note: "Due to Earth's axial precession, it will become the pole star around the year 7500." },
  "Gienah": { distanceLy: 72, type: "K3III — orange giant" },
  "Markab": { distanceLy: 133, type: "B9III — blue-white giant" },
  "Menkar": { distanceLy: 249, type: "M1.5IIIa — red giant" },
  "Zosma": { distanceLy: 58, type: "A4V — white main-sequence star" },
  "Graffias": { distanceLy: 530, type: "B1V — blue binary" },
  "Arneb": { distanceLy: 1300, type: "F0Ib — yellow-white supergiant" },
  "Zubeneschemali": { distanceLy: 185, type: "B8V — blue-white main-sequence star" },
  "Unukalhai": { distanceLy: 74, type: "K2III — orange giant" },
  "Sheratan": { distanceLy: 60, type: "A5V — white main-sequence star" },
  "Ruchbah": { distanceLy: 99, type: "A5V — binary system" },
  "Mufrid": { distanceLy: 37, type: "G0IV — yellow subgiant" },
  "Tarazed": { distanceLy: 460, type: "K3II — orange giant" },
  "Porrima": { distanceLy: 39, type: "F0V — binary system" },
  "Zubenelgenubi": { distanceLy: 77, type: "A3V — multiple system", note: "Wide enough to split into two stars with the naked eye." },
  "Cebalrai": { distanceLy: 82, type: "K2III — orange giant" },
  "Cursa": { distanceLy: 89, type: "A3III — white giant" },
  "Kornephoros": { distanceLy: 148, type: "G7IIIa — yellow giant" },
  "Rasalgethi": { distanceLy: 360, type: "M5Ib-II — red supergiant", note: "A variable star and one of the largest stars visible to the naked eye." },
  "Rastaban": { distanceLy: 380, type: "G2II — yellow giant" },
  "Algenib": { distanceLy: 390, type: "B2IV — blue-white subgiant" },
  "Alcyone": { distanceLy: 440, type: "B7III — blue-white giant", note: "The brightest star in the Pleiades cluster." },
  "Vindemiatrix": { distanceLy: 110, type: "G8III — yellow giant" },
  "Gomeisa": { distanceLy: 170, type: "B8Ve — blue-white star" },
  "Cor Caroli": { distanceLy: 110, type: "A0 — chemically peculiar star" },
  "Sadalsuud": { distanceLy: 610, type: "G0Ib — yellow supergiant" },
  "Sadalmelik": { distanceLy: 520, type: "G2Ib — yellow supergiant" },
  "Albireo": { distanceLy: 380, type: "K3II+B8V — double star", note: "A famous telescope target for its striking gold-and-blue color contrast." },
};
